Ajout de la javadoc dans javadoc/
dil-classroom/projet-egger_gehring_schaller_vogel pull request #104
Opened 2022-06-09 10:26 UTC by jorisSchaller

- Temps passé
 30'
- Qu'est-ce que cette PR va changer ?
Elle va ajouté un dossier contenant les fichiers html du site de javadoc
- Pourquoi l'a-t-on changé ?
La javadoc n'était pas disponible, maintenant elle est dans le repertoire javadoc/
- Comment l'a-t-on testé ?
ça n'a pas été testé vu que nous avons pas ajouté de code
- Est-ce que cette feature va encore évoluer ?
Oui lorsque du nouveau code va être ajouté, la documentation va être modifiée/ ajoutée et donc la javadoc générée sera changé.
Closes #89  closes #84

2022-06-14 12:55 UTC, Lollipoke requested changes
Pas mal de typos / petites fautes d'orthographe qu'il faudrait corriger pour avoir une javadoc en ordre

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/utils/Watcher.java
> +     * Cette methode est utilisé pour supprimer un callable a appeler lorsque la directoryToWatch
utilisée *
à appeler *

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/utils/Watcher.java
> +     * @param observer le sujet a supprimer
à supprimer *

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/utils/ParserContentFile.java
> + * Cette class est utilisée pour parser un fichier de contenu, elle sépare le contenu et les métadonée au délimiteur ---
classe *
métadonnées*

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Build.java
> + * s'attend a trouver les fichier de contenu dans content et le résultat de la compilation sera mis
à trouver les fichiers *

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Build.java
> +     * roorDirectory contient le fichier où se situe le site. Il est initialité automatiquement par
initialisé*

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Build.java
> +     * Cette methode determine si le rootDirectoryToTest est un dossier contenant un site statique initialisé ou non
détermine *

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Build.java
> +     * Cette methode génère le du html à partir de contenu markdown
du html ou le html ? Pas les deux

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Build.java
> +     * @param markdown Un string contenu le markdown
contenant *

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Build.java
> +     * cette methode execute l'action principale de la classe, ici le commande build qui construit
méthode exécute*
la commande build*

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Clean.java
> +     * Cette variable contient le chemin du site statique, elle est initialité automatiquement par
initialisée*

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Clean.java
> +     * cette methode execute l'action principale de la classe, ici le commande clean
méthode exécute*
la commande *

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Init.java
> +     * Cette variable contient le chemin du site statique, elle est initialité automatiquement par
initialisée *

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Init.java
> +     * cette methode execute l'action principale de la classe, ici le commande init
méthode exécute *
la commande*

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Serve.java
> +     * cette methode execute l'action principale de la classe, ici le commande serve
méthode exécute
la commande *

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Version.java
> + * Cette class implemente la commanded version du programme, et affiche la version du programme
implémente la commande *

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/commands/Version.java
> +            // get the version
Il faudrait plutôt mettre les commentaires en français non ?

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/utils/DirectoryDeleter.java
> + * Cette classe est fournis une seul méthode static : delete qui permet de supprimer un dossier
Cette classe fournit une seule méthode static*
(Enfin, je pense que c'est ce que tu voulais dire)

2022-06-14 12:55 UTC, Lollipoke commented on src/main/java/utils/DirectoryDeleter.java
> +     * @param file le fichier / dossier a supprimer
à supprimer*

2022-06-14 14:26 UTC, jorisSchaller commented
@Lollipoke ça devrait être bon, merci de ta relecture attentive

2022-06-15 19:41 UTC, jorisSchaller commented
@Lollipoke tous les changements sont là, j'ai encore trouvé une trace de commentaire en anglais que j'ai supprimé.

2022-06-15 20:25 UTC, Lollipoke requested changes
Désolée, il y a encore quelques petites erreurs ^^ Mais quasi rien !

2022-06-15 20:25 UTC, Lollipoke commented on src/main/java/commands/Clean.java
> +     * cette methode execute l'action principale de la classe, ici le commande clean
ça n'a pas été corrigé non plus ici

2022-06-15 20:25 UTC, Lollipoke commented on src/main/java/commands/Init.java
> +     * Cette variable contient le chemin du site statique, elle est initialité automatiquement par
Ici non plus

2022-06-15 20:25 UTC, Lollipoke commented on src/main/java/commands/Serve.java
> +            description = "répertoire racine root des fichier markdown")
il manque un -s à fichiers

2022-06-16 10:09 UTC, Lollipoke approved these changes
Maintenant c'est tout bon

2022-06-16 10:20 UTC, merged