Feature build commande
dil-classroom/projet-egger_gehring_schaller_vogel pull request #48
Opened 2022-03-31 13:33 UTC by vogelma

Closes #31
Une fois appliqué ce commit permettra de build un site depuis des fichiers markdown.
utilisation: build chemin/vers/le/site

2022-03-31 19:15 UTC, jorisSchaller requested changes
J'approuve lorsque tu remets le fichier de teste de la classe Statique

2022-03-31 19:16 UTC, jorisSchaller commented on test1/site/fichier2.md
> +a table
résolu par https://github.com/dil-classroom/projet-egger_gehring_schaller_vogel/pull/48/commits/be9484b1b0dc5a7947dfda093b856bbf8d27deaa

2022-04-05 06:58 UTC, vogelma commented on src/main/java/commands/Build.java
> +                System.out.println("Error: not a directory");
Tu peux vérifier maintenant j'ai fait les changements demandés.

2022-04-05 07:27 UTC, jorisSchaller approved these changes
ok c'est top merci :)

2022-04-05 07:28 UTC, merged